
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Museum
{

using System;
    using System.Collections.Generic;
    
public partial class Expon
{

    public int Exponat_ID { get; set; }

    public string Name_Exponat { get; set; }

    public string Description { get; set; }

    public int Zal { get; set; }

}

}
