
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Museum
{

using System;
    using System.Collections.Generic;
    
public partial class Kontaks
{

    public int ID_Kontaks { get; set; }

    public string Oficial_Name { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public string Mail { get; set; }

}

}
