
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Museum
{

using System;
    using System.Collections.Generic;
    
public partial class VistavVivod
{

    public int ID_Vistavka { get; set; }

    public string Exhibition_Name { get; set; }

    public string Opisanie { get; set; }

    public int Zal { get; set; }

}

}
